###register request
POST http://localhost:3300/auth/register
Content-Type: application/json

{
    "username" : "ali",
    "email" : "mohammaalid@gmail.com",
    "password" : "1234567",
    "mobile" : "09141241749",
    "confirm_password" : "1234567"

}


###login request
POST http://localhost:3300/auth/login
Content-Type: application/json
Authorization: Bearer {{$dotenv token}}

{
    "username" : "mohammad",
    "password" : "123456"
   

}


