### create Team
POST http://localhost:3300/team/create
Authorization: Bearer {{$dotenv token}}
Content-Type: application/json


{
   "name" : "mohammad A Team",
   "descriptaion" : "text for mohammad project is a amazing for programming",
   "username" : "mohammad_tab"
  
}


### get list All Team
GET http://localhost:3300/team/list
Authorization: Bearer {{$dotenv token}}
Content-Type: application/json


### get  Team By id
GET http://localhost:3300/team/63643718a4bba0038ef35d2c
Authorization: Bearer {{$dotenv token}}
Content-Type: application/json


### get My Team 
GET http://localhost:3300/team/me
Authorization: Bearer {{$dotenv token}}
Content-Type: application/json




### remove Team
DELETE http://localhost:3300/team/remove/63643718a4bba0038ef35d2c
Authorization: Bearer {{$dotenv token}}
Content-Type: application/json


### edit Team
PUT http://localhost:3300/team/update/63651b1f6625a74479eff467
Authorization: Bearer {{$dotenv token}}
Content-Type: application/json

{
   "name" : "mmd is very good boy",
   "descriptaion" : "mmd is very very  boy alah shahed doy"
}



### invite user to team
GET http://localhost:3300/team/invite/63662978036a6b3329874bbc/ali
Authorization: Bearer {{$dotenv token}}
Content-Type: application/json
