### get User Profile
GET http://localhost:3300/user/profile
Authorization: Bearer {{$dotenv token}}



### edit User Profile
POST http://localhost:3300/user/profile
Authorization: Bearer {{$dotenv token}}
Content-Type: application/json

{
    "first_name" : "ahmad",
    "last_name" : "ahmadi",
    "skills" : ["programmer","nodejs","express"]
  
}



### get All requests for user
GET http://localhost:3300/user/requests
Authorization: Bearer {{$dotenv token}}
Content-Type: application/json



### get Accepted user requests
GET http://localhost:3300/user/requests/accepted
Authorization: Bearer {{$dotenv token}}
Content-Type: application/json


### Accepted requests
GET http://localhost:3300/user/change-status-requests/636578082833812ecf4c83af/accepted
Authorization: Bearer {{$dotenv token}}
Content-Type: application/json

